### PR TITLE
Get rid of jackson-databind as a dependency

### PR DESCRIPTION
**Pull request by miikka**
It's a pretty heavy dependency to just have the date parsing code. This replaces the usage with Java 8 and Clojure standard library functions.

### CODE REVIEW

**Comment by miikka** [comment]
It doesn't support the former, but the latter works. It supports exactly the same syntax as Clojure's `#inst` literals. Hmm. I'm not sure if there's an easy way to add it back.

(If it hadn't supported the former syntax before, I wouldn't feel obligation to add support for it – RFC3339 should be good enough for everybody – but now that we supported it before, it breaks the backwards compatibility. I kind of see it as a bug that we have produced that as output, but it's hard to say what formats should be accepted.)

**Comment by Deraen** [comment]
If possible patterns can be listed, it is possible to build a formatter what accepts multiple patterns:

```java
DateTimeFormatter formatter = new DateTimeFormatterBuilder()
    .appendOptional(DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss.SSSSSS")
    .appendOptional(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss[.SSS]"
    .appendOptional(DateTimeFormatter.ofPattern("ddMMMyyyy:HH:mm:ss.SSS[ Z]")
    .toFormatter();
```

**Comment by Deraen** [comment]
Oh, the problem is not DateTimeFormatter, but `clojure.instant`.

Should be simple to parse dates ourselves, note fourth `Z` in the pattern to accept `+0000`:

```clj
user=> (def +format+ (-> (DateTimeFormatter/ofPattern "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX") (.withZone (ZoneId/of "UTC"))))
#'user/+format+
user=> (Instant/from (.parse +format+ "2014-02-18T18:25:37.000+0000"))
#object[java.time.Instant 0x982575a "2014-02-18T18:25:37Z"]
user=> (Instant/from (.parse +format+ "2014-02-18T18:25:37.000Z"))
#object[java.time.Instant 0xa265153 "2014-02-18T18:25:37Z"]
```

**Comment by ikitommi** [comment]
Would be nice to get this in..

**Comment by miikka** [comment]
I'll try to revisit this soon.

**Comment by miikka** [comment]
Rebased on master; now supports the Jackson default format as described by Tommi.

**Comment by ikitommi** [comment]
Awesome, let's release with this? (the cljdocs are broken due to force-push of tags anyway and need to re-release a version to get the docs out)

**Pull request merged**
