### PR TITLE
Handle s/or and s/and inside s/merge

### PR DESCRIPTION
**Pull request by Deraen**
It is possible some other specs should also look into anyOf and allOf but this should be good start.

### CODE REVIEW

**Comment by miikka** [comment]
I think that the test coverage fall is some kind of flakiness, because I don't think that there has been a meaningful change in the coverage in the file `spec_tools/core.cljc` which Coveralls points to.

**Comment by ikitommi** [comment]
seen this often, needed to add low-value tests to make it pass. can someone tune the parameters so that this would be... solved?

**Comment by miikka** [comment]
I suspect it's a bug in cloverage. For whatever reason some lines that were marked irrelevant before are now marked relevant (as they should). For what it's worth, I think that this project is complex enough that either adding enough tests for 100% coverage of `core.cljc` or removing the uncovered lines would be valuable.

**Comment by ikitommi** [comment]
set the threshold to `0.1` so that this should go away.

**Comment by ikitommi** [comment]
thanks!!

**Pull request merged**
