### PR TITLE
added or data-spec helper

### PR DESCRIPTION
**Pull request by yogthos**

### CODE REVIEW

**Comment by ikitommi** [comment]
The forms were not correct, otherwise awesome, thanks! Tried to fix (and test) the form in #101

**Comment by yogthos** [comment]
oh sorry about that, and glad I helped :)

**Comment by ikitommi** [comment]
few more things going into 0.6.0, but the changes are in clojars:

```clj
[metosin/spec-tools "0.6.0-20180130.055154-3"]
```

**Comment by yogthos** [comment]
👍

**Pull request merged**
