### PR TITLE
bugfix to make the coercion work properly with s/or

### LINKED ISSUE #178: strip-extra-keys-transformer not working with s/or
Given the following specs

```clojure
(ns or-spec-bug
  (:require [clojure.spec.alpha :as s]
            [spec-tools.core :as st]))

(s/def ::car (st/spec (s/keys :req-un [::doors])))

(s/def ::bike (st/spec (s/keys :req-un [::wheels])))

(s/def ::vehicle (st/spec (s/or :car ::car
                                :bike ::bike)))

(def chevy {:doors 4})

(st/conform ::vehicle chevy)
=> [:car {:doors 4}]

```

Since ```chevy``` is a ```car``` which is also a ```vehicle```, I would expect ```coerce``` with ```strip-extra-keys``` to return the same for ```car``` and ```vehicle``` but it doesn't: 

```clojure
(st/coerce ::car chevy st/strip-extra-keys-transformer)
=> {:doors 4}
(st/coerce ::vehicle chevy st/strip-extra-keys-transformer)
=> {}
```

### PR DESCRIPTION
**Pull request by wandersoncferreira**
Fixes #178 . The solution is a bit more convoluted than I expected because of the special case for `clojure.core/any?` forms that would introduce a bug if I stopped the reduce operation when I first get a valid data from a or spec.

The example provided in the issue is now working as expected:

```clj
(st/coerce ::vehicle chevy st/strip-extra-keys-transformer)
;; => {:doors 4}
```

### CODE REVIEW

**Comment by wandersoncferreira** [comment]
I did a bit more of investigation about this   `any` workaround. What happened was the following: 

Consider these specs:

```clj
(s/def ::car (st/spec (s/keys :req-un [::doors])))
(s/def ::bike (st/spec (s/keys :req-un [::wheels])))
(s/def ::tires (s/coll-of (s/and int?) :into #{}))
(s/def ::vehicle (s/or :car ::car
                       :bike ::bike))
(s/def ::new-vehicle (s/map-of
                      keyword?
                      (s/or :vehicle ::vehicle
                            :tires (s/coll-of (s/and int?) :into {}))))
```

The issue happened in one of the specs in the test suite that used the `(s/coll-of (s/and int?) :into {})` construct. Because, if you define the coll-of as a "unnamed spec" the current implementation will leave the `:into {}` part as a separate iteration in the recursive path performed during the coercion.

Therefore you should be expecting this?
```clj
(st/coerce ::new-vehicle {:rodas [1 "1" 3]} st/strip-extra-keys-transformer)
;; => {:rodas #{1 "1" 3}}
```
But you will get
```clj
(st/coerce ::new-vehicle {:rodas [1 "1" 3]} st/strip-extra-keys-transformer)
;; => {:rodas [1 "1" 3]}
```

I also noticed that when this happens, the `:form spec` of the created spec inside the `walk :or ` implementation is of the `clojure.core/any` therefore I skipped to the old behavior as soon as I encounter this situation.

However, now during my exploration I found that if you defined the `(s/coll-of..)` before and use the fullqualified name instead, it would work without the extra workaround.

```clj
(s/def ::new-vehicle (s/map-of
                      keyword?
                      (s/or :vehicle ::vehicle
                            :tires ::tires)))
```
Seems like the "unnamed" spec lacks something that `(st/create-spec ..)` cannot infer properly.

I'll push some tests.

**Comment by wandersoncferreira** [comment]
The breaking test was https://github.com/metosin/spec-tools/blob/6d1ffd4e52eb6082fe444e2bc58cc32def45494d/test/cljc/spec_tools/core_test.cljc#L427

**Comment by wandersoncferreira** [comment]
@ikitommi I will study this better today and tomorrow. I started to investigate the issue #212 and it seems related somehow to the problem I described earlier. Need more time to look in more depth.

**Comment by wandersoncferreira** [comment]
@ikitommi Now this is correct, I improved the mechanism to perform the validity of the coerced value and all went more smoothly now. There is not special case to handle. (Y)

**Comment by ikitommi** [comment]
Awesome, thanks!

**Comment by ikitommi** [comment]
Simplified a bit more: https://github.com/metosin/spec-tools/commit/f0bd074b9a31cb09f0924b8c08db5a3ea0ca71a5. Tests pass, does that look correct?

**Comment by wandersoncferreira** [comment]
Sure! Great, seems like `specize` has an implementation to `fn` interfaces, didn't know that.

**Pull request merged**
