### PR TITLE
fix string-conforming for number? predicate

### LINKED ISSUE #92: String conforming to number? fails for integers
```clojure
(spec-tools.spec/number? 1)
=> true
(spec-tools.core/conform spec-tools.spec/number? 1 spec-tools.core/string-conforming)
=> :clojure.spec.alpha/invalid
```
i think, the issue here is, that `number?` is classified as a `double` and `string->double` only checks whether the input is a `double?` before trying `Double/parseDouble`.
Since `Double/parseDouble` expects a string, an exception is thrown and `::s/invalid` is returned.

### PR DESCRIPTION
**Pull request by benalbrecht**
fixes #92

### CODE REVIEW

**Comment by ikitommi** [comment]
The error is expected as the functions now only transform, not validate. You can remove the test. Also, the `cond` can now be `if`.

Would you have time to fix the other functions (and tests) too?

**Comment by benalbrecht** [comment]
i've pushed a new commit that changes all string-conforming fns

**Comment by ikitommi** [comment]
Looks great, thanks a lot!!

**Comment by ikitommi** [comment]
I changed the exception-path also to return the original value. There is `[metosin/spec-tools "0.6.0-20171215.064849-1"]` with this in it.

**Pull request merged**
