### PR TITLE
Fix #214

### LINKED ISSUE #214: spec-tools.parse-test does not get run
These namespaces are not mentioned in `doo_runner.cljs`, so they never get run:
```
spec-tools.parse-test
spec-tools.spec-test
spec-tools.spell-test
```
When I do include them, there are two failures in the `spec-tools.parse-test`:

```
FAIL in (parse-test) (cljs/test.js:433:14)
predicate
expected: (= {:spec double?, :type :double} (parse/parse-spec (quote clojure.core/double?)) (parse/parse-spec double?))
  actual: (not (= {:spec #object[cljs$core$double_QMARK_], :type :double} {:spec #object[cljs$core$double_QMARK_], :type :double} {:type nil}))

FAIL in (parse-test) (cljs/test.js:433:14)
s/multi-spec
expected: (= {:type :multi-spec, :spec-tools.parse/key :spec-tools.parse-test/h, :spec-tools.parse/dispatch {:type-a :spec-tools.parse-test/ha, :type-b :spec-tools.parse-test/hb}} (parse/parse-spec :spec-tools.parse-test/multi))
  actual: (not (= {:type :multi-spec, :spec-tools.parse/key :spec-tools.parse-test/h, :spec-tools.parse/dispatch {:type-a :spec-tools.parse-test/ha, :type-b :spec-tools.parse-test/hb}} {:type nil}))
```

### PR DESCRIPTION
**Pull request by akond**

### CODE REVIEW

**Comment by viesti** [comment]
So I tried running the tests locally on the forked repo and got the same error. Didn't figure out the cause yet. Could there be something missing from the commit that exists in the local working copy?

**Comment by akond** [comment]
My working copy is out of the question. I cloned the repo once again into an empty directory and tests run fine. Maybe there is a problems with tools versions, such as phantom, node or whatnot?

**Comment by viesti** [comment]
You can run the test in the Travis container environment locally via the following:

```
0% cd /tmp
0% git clone git@github.com:akond/spec-tools.git
0% cd spec-tools
0% docker pull travisci/ci-sardonyx:packer-1558623664-f909ac5
packer-1558623664-f909ac5: Pulling from travisci/ci-sardonyx
...
0% docker run --rm -v `pwd`:/spec-tools -it travisci/ci-sardonyx:packer-1558623664-f909ac5 /bin/bash -l
root@a5da679cbd7f:/# su - travis
travis@a5da679cbd7f:~$ cd /spec-tools/
travis@a5da679cbd7f:/spec-tools$ ./scripts/test.sh cljs
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Retrieving jonase/eastwood/0.3.5/eastwood-0.3.5.pom from clojars
....
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
WARNING: Use of undeclared Var spec-tools.transform-test/BigDecimal at line 11 test/cljc/spec_tools/transform_test.cljc
WARNING: Use of undeclared Var spec-tools.transform-test/BigDecimal at line 11 test/cljc/spec_tools/transform_test.cljc

;; ======================================================================
;; Testing with Phantom:


Testing spec-tools.core-test

Testing spec-tools.impl-test

Testing spec-tools.transform-test

Testing spec-tools.data-spec-test

Testing spec-tools.json-schema-test

Testing spec-tools.parse-test

Testing spec-tools.spec-test

Testing spec-tools.spell-test

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data simple specs
expected: (s/explain-data (spell/closed (s/keys :opt-un [:spec-tools.spell-test/config])) invalid-options)
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data simple specs
expected: (s/explain-data (spell/closed (s/keys :opt-un [:spec-tools.spell-test/config])) invalid-config)
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data composite specs
expected: (s/explain-data (spell/closed (s/merge (s/keys :opt-un [:spec-tools.spell-test/config]) (s/keys :opt-un [:spec-tools.spell-test/name]))) {:namez "kikka"})
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data explain-str
expected: (str/includes? (spell/explain-str (spell/closed (s/keys :opt-un [:spec-tools.spell-test/config])) invalid-options) "Misspelled map key")
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data explain
expected: (str/includes? (with-out-str (spell/explain (spell/closed (s/keys :opt-un [:spec-tools.spell-test/config])) invalid-options)) "Misspelled map key")
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data data-specs
expected: (s/explain-data spec invalid-options)
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

ERROR in (spell-test) (spell_spec/alpha.js:82:48)
explain-data data-specs
expected: (s/explain-data spec invalid-config)
  actual: #object[TypeError TypeError: undefined is not a function (evaluating 'p1__13097_SHARP_.startsWith(":")')]

Testing spec-tools.visitor-all-test

Testing spec-tools.visitor-test

Testing spec-tools.swagger.core-test

Testing spec-tools.swagger.spec-test

Ran 74 tests containing 544 assertions.
0 failures, 7 errors.
Subprocess failed
travis@a5da679cbd7f:/spec-tools$
```

I hope the above helps in hunting down the problem :)

**Comment by akond** [comment]
I think I found it. The source of the error is in the other library, namely `spell-spec.alpha`.
I'm going to create a pull request there before fixing this one.

**Comment by akond** [comment]
It just came to me: the lib we're trying to fix is not under active development. I don't think the author is going to accept a PR. So what do we do?

**Comment by ikitommi** [comment]
We can't use `spell-spec.alpha` as a package: if someone adds a direct dependency to it, there is no knowing which implementation get's used. We could change `spell-spec.alpha` to `spec-tools.spell-spec`. Also would be polite to add a comment that we'll swap back to original library if it gets patched to support these. 

Also, would like to get a clean commit on the import of `spell-spec` and the fixes done to it to keep track of the changes.

Otherwise, looking good.

**Comment by akond** [comment]
I'll create another PR then.

**Pull request closed without merging**
